### ISSUE TITLE
Compile examples in Travis builds

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/questions-and-answers#42]
Many repos have examples that are compiled separately... that should not mean not having them tested via Travis!

---

- [x] [yarp-devices](https://github.com/roboticslab-uc3m/yarp-devices/tree/e26db48e8a0d6582df8ca18583b55f8b3bfba898/examples/cpp)
- [x] [speech](https://github.com/roboticslab-uc3m/speech/tree/196cff4a824c625b715b6f4b6d1520153060b0b8/examples/cpp/espeakExample)
- [x] [kinematics-dynamics](https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/3d2159b808dfda5737283390ee4b426e1ac27fe8/examples/cpp)
- [x] [tools](https://github.com/roboticslab-uc3m/tools/tree/2fad5258be2156cb270bbcf51a7cdd1f6159408f/examples/cpp/examplePlaybackThread)
- [x] [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/tree/c8d6a538f8a4faafa2a32371b711147efe69fff6/examples/cpp/robotDraw)

**Comment by PeterBowman** [comment]
We could have avoided https://github.com/roboticslab-uc3m/tools/issues/10#issuecomment-357375402 if examples were covered by tests.

Also, keep this in mind: roboticslab-uc3m/best-practices#21. Which boils down to: place Travis instructions that relate to building the examples in the `before_script` YAML section.

**Comment by PeterBowman** [comment]
Added TODO list to description.

**Comment by PeterBowman** [comment]
CMake [alias targets](https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#alias-targets) may be useful here.

**Comment by PeterBowman** [comment]
Several examples are not even written in C/C++. Perhaps we could test bindings, too.

**Comment by PeterBowman** [comment]
Idea: `add_subdirectory(examples)` from root *CMakeLists.txt*, set `ENABLE_examples=ON` in Travis (defaults to OFF)?

**Comment by jgvictores** [comment]
IMHO:
1. CI is great, and it would be great to have `examples` at least compiled via Travis.
2. I'm happy with self-contained `examples`. If we `add_subdirectory(examples)`, wouldn't it be catching repo-level dependencies rather than forcing them to be cited explicitly?

As a solution, maybe forcing Travis to enter `examples` and compile separately?

**Comment by PeterBowman** [comment]
ASWJ:

* Examples are going to remain as self-contained projects, no matter what.
* We could instruct root CMakeLists.txt to traverse these project so that everything is built together (main project + examples). However, this simple trick would force us to hide a few lines behind an `if` clause, for instance [these `find_package() instructions`](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/3d2159b808dfda5737283390ee4b426e1ac27fe8/examples/cpp/exampleScrewTheoryTrajectory/CMakeLists.txt#L6-L9). Since we aim to illustrate best practices and usage of our libraries/APIs (targeted at devs), such hacks would be certainly misleading.
* Make Travis configure and compile the examples separately in the `before_script` section of .travis.yml.

**Comment by jgvictores** [comment]
@PeterBowman Thanks!!!
