### ISSUE TITLE
cards in Thingsboard professional version

### ISSUE THREAD

**Issue by 01nitin** [roboticslab-uc3m/questions-and-answers#98]
Hello everyone,
I'm nitin pandey,

I want to know that how can I add the javaScript condition in alarm cards in professional version of thingsboard. if the temperature level is high then it should be the RED background color and if temperature is normal then it should GREEN with background color. i have added the images of community version,

thanks in advance

![image](https://github.com/roboticslab-uc3m/questions-and-answers/assets/116839685/edcbd318-16eb-4f02-88de-fcd7c2446a8b)

**Comment by PeterBowman** [comment]
Hello, @01nitin. This is a repository devoted to answering questions related to the roboticslab-uc3m organization, its community and projects. I'm afraid this issue is therefore out of topic. Please resort to more generic search aggregators and developer communities such as StackOverflow/Google. Thank you for your understanding.
